#!/usr/bin/env dart
// make_resource_file.dart
//
// Embeds a binary file's bytes as a lazy Uint8List constant in a generated
// Dart source file.  Run this manually whenever the resource changes — it is
// NOT part of the Flutter build.
//
// Usage:
//   dart tool/make_resource_file.dart -f <input_file> -n <ResourceName> [-o <output_dir>]
//
// Arguments:
//   -f  Path to the input file (e.g. PlayerData.zip)
//   -n  Resource name, used as the Dart symbol prefix and output filename
//       (e.g. "PlayerDataFile" → PlayerDataFile.dart + kPlayerDataFile getter)
//   -o  Output directory (default: current directory)
//
// Example:
//   dart tool/make_resource_file.dart -f PlayerData.zip -n PlayerDataFile
//   → Generates PlayerDataFile.dart with a kPlayerDataFile Uint8List getter.
//
// The generated file uses lazy base64 decoding and caches the result, so the
// cost of decoding is paid only once per app session.

import 'dart:convert';
import 'dart:io';

// Base64 line width used when splitting the encoded string into chunks.
// Shorter chunks produce more readable diffs; 76 is the MIME standard width.
const int _kChunkSize = 76;

void main(List<String> args) {
  String? inputFile;
  String? resourceName;
  String? outputDir;

  for (int i = 0; i < args.length - 1; i++) {
    if (args[i] == '-f') inputFile  = args[i + 1];
    if (args[i] == '-n') resourceName = args[i + 1];
    if (args[i] == '-o') outputDir  = args[i + 1];
  }

  if (inputFile == null || resourceName == null) {
    stderr.writeln('Usage: dart tool/make_resource_file.dart '
        '-f <input_file> -n <ResourceName> [-o <output_dir>]');
    stderr.writeln('');
    stderr.writeln('  -f  Input file to embed');
    stderr.writeln('  -n  Resource name (Dart symbol prefix + output filename)');
    stderr.writeln('  -o  Output directory (default: current directory)');
    exit(1);
  }

  // Validate input
  final src = File(inputFile);
  if (!src.existsSync()) {
    stderr.writeln('Error: file not found: $inputFile');
    exit(1);
  }

  // Read and encode
  final bytes     = src.readAsBytesSync();
  final b64       = base64Encode(bytes);
  final chunks    = _splitIntoChunks(b64, _kChunkSize);

  // Dart identifiers derived from resourceName
  // Public getter:  kPlayerDataFile
  // Private chunks: _kPlayerDataFileChunks
  // Private cache:  _kPlayerDataFileCache
  final cap     = '${resourceName[0].toUpperCase()}${resourceName.substring(1)}';
  final getter  = 'k$cap';
  final priv    = '_k$cap';

  // Build output
  final buf = StringBuffer()
    ..writeln('// Generated by tool/make_resource_file.dart — DO NOT EDIT.')
    ..writeln('// Source    : $inputFile')
    ..writeln('// Size      : ${_fmtSize(bytes.length)}')
    ..writeln('// Chunks    : ${chunks.length} × $_kChunkSize chars (base64)')
    ..writeln('// Generated : ${DateTime.now().toIso8601String()}')
    ..writeln('')
    // Silence the linter — long base64 strings are unavoidable here.
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln('')
    ..writeln("import 'dart:convert';")
    ..writeln("import 'dart:typed_data';")
    ..writeln('')
    ..writeln('/// Bytes of [$inputFile] embedded as a Dart constant.')
    ..writeln('/// Decoded from base64 lazily on first access and cached.')
    ..writeln('Uint8List get $getter => ${priv}Cache ??= base64Decode(${priv}Chunks.join());')
    ..writeln('Uint8List? ${priv}Cache;')
    ..writeln('')
    ..writeln('const List<String> ${priv}Chunks = [');

  for (final chunk in chunks) {
    buf.writeln("  '$chunk',");
  }
  buf.writeln('];');

  // Write output file
  final outPath = outputDir != null
      ? '${outputDir.trimRight().replaceAll(RegExp(r'[\\/]$'), '')}/$resourceName.dart'
      : '$resourceName.dart';
  final outFile = File(outPath);
  outFile.writeAsStringSync(buf.toString());

  final outSize = outFile.lengthSync();
  stdout.writeln('✓ Generated: ${outFile.path}');
  stdout.writeln('  Input  : $inputFile (${_fmtSize(bytes.length)})');
  stdout.writeln('  Output : ${outFile.path} (${_fmtSize(outSize)} source)');
  stdout.writeln('  Symbol : $getter  (Uint8List, lazy-decoded)');
  stdout.writeln('');
  stdout.writeln('To use it, import the generated file and access `$getter`.');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

List<String> _splitIntoChunks(String s, int size) {
  final result = <String>[];
  for (int i = 0; i < s.length; i += size) {
    result.add(s.substring(i, (i + size).clamp(0, s.length)));
  }
  return result;
}

String _fmtSize(int bytes) {
  if (bytes < 1024)           return '$bytes B';
  if (bytes < 1024 * 1024)   return '${(bytes / 1024).toStringAsFixed(1)} KB';
  return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
}
